# -*- coding: utf-8 -*-
"""ejercicio 3 parte 3 Prob&Est.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1DmXVmf1a5VEKGi0X1eyU-6DnzFnAP4s2
"""

import statistics
import matplotlib.pyplot as plt
import numpy as np
import pandas as pd
import seaborn as sns
from scipy.stats import poisson
from sklearn.preprocessing import StandardScaler

L = 30

r1 = poisson.rvs(L,size = 1000)
r2 = poisson.rvs(L,size = 10000)
r3 = poisson.rvs(L,size = 100000)
r4 = poisson.rvs(L,size = 1000000)


sns.boxplot(r1)

sns.boxplot(r2)

sns.boxplot(r3)

sns.boxplot(r4)

sns.displot(x=r1)

sns.displot(x=r2)

sns.displot(x=r3)

sns.displot(x=r4)

mediana1 = statistics.median(r1)
mediana2 = statistics.median(r2)
mediana3 = statistics.median(r3)
mediana4 = statistics.median(r4)

print("Mediana de muestra 1: ", mediana1)
print("Mediana de muestra 2: ", mediana2)
print("Mediana de muestra 3: ", mediana3)
print("Mediana de muestra 4: ", mediana4)

moda1 = statistics.mode(r1)
moda2 = statistics.mode(r2)
moda3 = statistics.mode(r3)
moda4 = statistics.mode(r4)

print("Moda de muestra 1: ", moda1)
print("Moda de muestra 2: ", moda2)
print("Moda de muestra 3: ", moda3)
print("Moda de muestra 4: ", moda4)

media1 = r1.mean()
media2 = r2.mean()
media3 = r3.mean()
media4 = r4.mean()

print("Media de muestra 1: ", media1)
print("Media de muestra 2: ", media2)
print("Media de muestra 3: ", media3)
print("Media de muestra 4: ", media4)

varianza1 = r1.var()
varianza2 = r2.var()
varianza3 = r3.var()
varianza4 = r4.var()

print("Varianza de muestra 1: ", varianza1)
print("Varianza de muestra 2: ", varianza2)
print("Varianza de muestra 3: ", varianza3)
print("Varianza de muestra 4: ", varianza4)